### ISSUE TITLE
semantic-release plugin support Gitea?

### ISSUE THREAD

**Issue by Veitor** [arlac77/gitea-repository-provider#159]
Is this plugin of [semantic-release](https://github.com/semantic-release/semantic-release) and support Gitea?

**Comment by arlac77** [comment]
currently not but it can be the base of such a plugin

**Comment by arlac77** [comment]
found it:
there is actually a

**repos/{owner}/{repo}/contents/{file}?ref=myBranch**

url

**Comment by saitho** [comment]
@Veitor I've started working a plugin which allows pushing release notes to Gitea. If that's what you are looking for: https://github.com/saitho/semantic-release-gitea
Currently testing and fixing bugs. Might take a couple of weeks to finish. ;)
